# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spacelist < Formula
  desc "A beautiful terminal UI for viewing all windows across your Aerospace window manager spaces"
  homepage "https://github.com/magicmark/spacelist"
  version "0.5.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/magicmark/spacelist/releases/download/v0.5.1/spacelist_0.5.1_darwin_amd64.tar.gz"
    sha256 "4d3fa552996a326e2b3a05568efd5906c88027dd707ae740906f3138df1ebd13"

    def install
      bin.install "spacelist"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/magicmark/spacelist/releases/download/v0.5.1/spacelist_0.5.1_darwin_arm64.tar.gz"
    sha256 "4dfb7b62aaad7b501c2353b6c8f599ec0a5661308efb29b2b902686c2dc28270"

    def install
      bin.install "spacelist"
    end
  end

  def caveats
    <<~EOS
      spacelist is now installed!

      Requirements:
        - Aerospace window manager must be installed

      Run 'spacelist' to start the application.
    EOS
  end
end
