# This file was generated by GoReleaser. DO NOT EDIT.
cask "spacelist" do
  name "spacelist"
  desc "A beautiful terminal UI for viewing all windows across your Aerospace window manager spaces"
  homepage "https://github.com/magicmark/spacelist"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spacelist"
  depends_on formula: [
      "aerospace",
    ]

  on_macos do
    on_intel do
      url "https://github.com/magicmark/spacelist/releases/download/v#{version}/spacelist_#{version}_darwin_amd64.tar.gz"
      sha256 "6a49e3390756901ddeb5e4a0a53672fd44960f65604a7c59300f336fb8e55a6e"
    end
    on_arm do
      url "https://github.com/magicmark/spacelist/releases/download/v#{version}/spacelist_#{version}_darwin_arm64.tar.gz"
      sha256 "6d03432481c2afcdbf099add3665e01aabc34ed27d09527fb83213f47710f051"
    end
  end

  caveats do
    "spacelist is now installed!"
    ""
    "Requirements:"
    "  - Aerospace window manager must be installed"
    ""
    "Run 'spacelist' to start the application."
  end

  # No zap stanza required
end
